name: Deploy

on:
  push:
    branches: [ main ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - run: |
          npm ci
          npm run build
          mv index.html index.css dist/
      - uses: actions/checkout@v3
        with:
          ref: pages
          clean: false
      - run: |
          mv dist/index.html dist/index.css ./
          git add *.html *.css dist/
      - run: |
          git config user.name "Yoshihiro Tanaka"
          git config user.email "contact@cordea.jp"
          git commit -m "update"
          git push
